Develop
eduardovrocha/municipes-service pull request #1
Opened 2021-07-19 11:27 UTC by eduardovrocha

resources, validações, ambiente de teste com cobertura básico de requests/helpers/views/models

2021-07-19 22:48 UTC, ricardopacheco commented on .ruby-version
> +ruby-2.7.2@om30
Você utiliza RVM?

caso utilize me parece incorreto essa configuração (posso estar errado já que o RVM mudou e faz tempo que não uso). Para configurar gemsets, ele usa um arquivo específico `.ruby-gemset`.

Com o avanço do bundler, gemsets estão obsoletas (mesmo usando RVM). Não tá errado, mas, o arquivo `.ruby-version` é usado por outros gerenciadores, como o asdf e o rbenv. Por isso a sugestão.

2021-07-19 23:17 UTC, ricardopacheco requested changes
Bom, houve uma violação na regra de negócio por isso o PR não poderá ser aprovado. Após a refatoração das mesmas e outras coisas, pretendo rodar localmente a aplicação para ver os testes funcionais/rotas/views.

2021-07-19 23:17 UTC, ricardopacheco commented on app/controllers/citizens_controller.rb
> +  def destroy
Olha, isso aqui realmente é grave! Essa é uma falta de atenção a leitura da regra de negócio, é um erro humano, mas, isso é tipo erro fatal em qualquer implementação de negócio!

Além de ter ficado claro na documentação, nosso líder técnico deixou isso AS VISTAS na daily. É uma dupla falta de atenção Eduardo. 

Estou realmente dando um salve geral, erros podem ser cometidos, mas, não com tamanha falta de atenção. Que o chamado sirva de lição para os próximos casos.

2021-07-19 23:17 UTC, ricardopacheco commented on app/controllers/citizens_controller.rb
> +      format.html { redirect_to citizens_url, notice: "Citizen was successfully destroyed." }
Add I18n message.

2021-07-19 23:17 UTC, ricardopacheco commented on app/helpers/addresses_helper.rb
> +module AddressesHelper
Código não utilizado deve ser removido.

2021-07-19 23:17 UTC, ricardopacheco commented on app/helpers/citizens_helper.rb
> +module CitizensHelper
Código não utilizado deve ser removido.

2021-07-19 23:17 UTC, ricardopacheco commented on app/models/citizen.rb
> +  has_many :addresses
Não seria um pra um de acordo com a doc? Mas ok, isso também pode ser feito.

Lembrando que falta opções ao has_many. O que acontece com o address caso o citizen seja removido (você permitiu acima, lembra?). Logo, o endereço deve ser removido junto.

Nesses casos dizemos ao has_many pra fazer isso add a opção (dependend: :destroy).

2021-07-19 23:17 UTC, ricardopacheco commented on app/views/addresses/_address.json.jbuilder
> +json.extract! address, :id, :cep, :full_place, :created_at, :updated_at
Usando json views, gostei! Só lembrando que jbuilder devemos ter cuidado. Tem ótima legibilidade e flexibilidade, porém, é terrível sua performance.

2021-07-19 23:17 UTC, ricardopacheco commented on app/views/addresses/_form.html.erb
> +      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>
Aproveita e utiliza I18n no contexto da linha inteira uai rs

2021-07-19 23:17 UTC, ricardopacheco commented on app/views/addresses/index.json.jbuilder
> +json.array! @addresses, partial: "addresses/address", as: :address
Partials! Boa! 👍

2021-07-19 23:17 UTC, ricardopacheco commented on config/routes.rb
> -  resources :municipes
Excelente a troca! Removeu a dissonância cognitiva no código. Inclusive deveríamos seguir isso nos projetos, porém, devido a regra exclusivas, nosso código é em pt-BR em muitos trechos. Como fora uma regra, não tem erro.

Porém, prefiro one language for all, conforme vc fez. Correto 👍

2021-07-19 23:17 UTC, ricardopacheco commented on db/data/20210716210231_add_citizens.rb
> +class AddCitizens < SeedMigration::Migration
Eu vi a inclusão dessa gem, e, fique curioso para o que ela servia. 

Porque add uma dependência como ela ao invés de já usarmos o seed de dados nativo do próprio rails?

2021-07-19 23:17 UTC, ricardopacheco commented on db/migrate/20210716195108_create_addresses.rb
> +      t.jsonb :full_place
Gostei de como vc pensou aqui, eu faço coisas similares. Mas, você esqueceu de um baita detalhe importante. O que seria? 🤔

2021-07-19 23:17 UTC, ricardopacheco commented on db/seeds.rb
> +ActiveRecord::Base.transaction do
Whaaat? 🤕

2021-07-19 23:17 UTC, ricardopacheco commented on spec/factories/addresses.rb
> +    cep { "MyString" }
Você utilizou Faker na sua gem de seed de dados. Porque não utilizar nas factories?

2021-07-19 23:17 UTC, ricardopacheco commented on spec/factories/citizens.rb
>      name { "MyString" }
Você utilizou Faker na sua gem de seed de dados. Porque não utilizar nas factories?

2021-07-19 23:17 UTC, ricardopacheco commented on spec/helpers/addresses_helper_spec.rb
> +RSpec.describe AddressesHelper, type: :helper do
Se helpers são vazios, testes para o mesmo não fazem sentido (nem mesmo pending). Se o helper for removido (conforme sugeri), remover também os testes.

Se vai criá-lo no futuro, cria no futuro conforme a sua necessidade no futuro.

2021-07-19 23:17 UTC, ricardopacheco commented on spec/helpers/citizens_helper_spec.rb
> +RSpec.describe CitizensHelper, type: :helper do
Mesmo comentário acima.

2021-07-19 23:17 UTC, ricardopacheco commented on spec/models/address_spec.rb
>    pending "add some examples to (or delete) #{__FILE__}"
O model já tinha algumas validações. Já valeria aquele teste maroto. Mas, aqui entendi que tá pending e faz sentido se vai add em commits posteriores.

2021-07-19 23:17 UTC, ricardopacheco commented on spec/models/citizen_spec.rb
> +RSpec.describe Citizen, type: :model do
Mesmo comentário acima.

2021-07-19 23:17 UTC, ricardopacheco commented on spec/routing/addresses_routing_spec.rb
> +RSpec.describe AddressesController, type: :routing do
Gostei da inserção do teste de rotas! 👍

2021-07-19 23:17 UTC, ricardopacheco commented on spec/views/addresses/edit.html.erb_spec.rb
> +    @address = assign(:address, Address.create!(
Aqui você precisa ter uma boa razão pra instanciar diretamente o model, já que usa os factories (eles existem pra essa finalidade). Como eu vi que tem factories na app. Então, refatore usando o mesmo.

Fica mais simples e elegante que o código acima, inclusive.

2021-07-20 04:20 UTC, gumiguelote commented on README.md
> +## backend todo:
Concordo, e inclusive recomento o uso do trello ou um kanban mais simples.

2021-07-20 04:22 UTC, gumiguelote commented on app/controllers/addresses_controller.rb
> +      format.html { redirect_to addresses_url, notice: "Address was successfully destroyed." }
No caso do destroy não precisa nem existir!

2021-07-20 04:24 UTC, gumiguelote commented on .ruby-version
> +ruby-2.7.2@om30
Inclusive recomendo o uso do asdf, uma boa sugestão do Ricardo, usei e recomendo

2021-07-20 04:26 UTC, gumiguelote commented on README.md
> +**01::** instalar docker desktop
Eu daria uma melhorada no seguinte sentido, ou todo em inglês, ou todo em português. Ou até um principal em uma língua e outro em outra língua, misturar itens português com não fica muito legal não. ;)

2021-07-20 04:39 UTC, gumiguelote requested changes
É necessária uma revisão do código com as observações feitas.

2021-07-20 04:39 UTC, gumiguelote commented on app/controllers/citizens_controller.rb
> +  # GET /citizens/new
Esses comentários são realmente necessários?

2021-07-20 04:39 UTC, gumiguelote commented on db/data/20210716210231_add_citizens.rb
> +                      :cns => "05394738625",
Aqui não seria correto já colocar um CNS correto?

2021-07-20 10:47 UTC, italopires requested changes

2021-07-20 10:47 UTC, italopires commented on app/controllers/addresses_controller.rb
> +    def set_address
Como boa prática, a identação entre o private e os proxímos metodos, devem está na mesma identação, e ter uma linha entre o `private` e o próximo método.

2021-07-20 10:47 UTC, italopires commented on app/controllers/addresses_controller.rb
> +class AddressesController < ApplicationController
Sugiro dá uma olhada em `nested attributes`, você não precisaria criar um controller separado para `address`, pois estaria sendo `builded` dentro do controller de `citizen` mesmo.

dá uma olhada:

https://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html

2021-07-20 10:47 UTC, italopires commented on app/controllers/addresses_controller.rb
> +        format.html { redirect_to @address, notice: "Address was successfully created." }
Você está realmente utilizando as duas responses `html` e `json`?

2021-07-20 10:47 UTC, italopires commented on app/controllers/citizens_controller.rb
> +      format.json { head :no_content }
se não está sendo utilizado, remove

2021-07-20 10:47 UTC, italopires commented on app/controllers/citizens_controller.rb
> +    def set_citizen
Ajustar a identação

2021-07-20 10:47 UTC, italopires commented on config/routes.rb
> +  resources :citizens do
É necessário utilizar a action destroy também? Removeria rotas desnecessárias

2021-07-20 10:47 UTC, italopires commented on config/routes.rb
> +    resources :addresses
Removeria rotas não utilizadas

2021-07-20 10:47 UTC, italopires commented on db/seeds.rb
> +SeedMigration::Migrator.bootstrap(20210716210231)
O que essa gem tem, que o seed nativo do rails não tem? Pra entender qual a necessidade de utilizar essa gem

2021-07-20 10:47 UTC, italopires commented on spec/requests/citizens_spec.rb
> +      Citizen.create! valid_attributes
Utilizar factory para os objetos, remover os skips. Aqui nesse arquivo você não está testando nada

2021-07-20 10:47 UTC, italopires commented on spec/routing/addresses_routing_spec.rb
> +    it "routes to #destroy" do
Você está utilizando essa rota?

2021-07-20 10:47 UTC, italopires commented on spec/routing/citizens_routing_spec.rb
> +    it "routes to #destroy" do
Essa rota é necessaria?

2021-07-20 10:47 UTC, italopires commented on app/controllers/citizens_controller.rb
> +class CitizensController < ApplicationController
Faltou teste para esse controller

2021-07-20 10:47 UTC, italopires commented on app/models/citizen.rb
> +class Citizen < ApplicationRecord
Faltou teste para esse model

2021-07-20 10:47 UTC, italopires commented on app/models/address.rb
> +  belongs_to :citizen
Faltou teste para esse model

2021-07-20 11:11 UTC, ricardopacheco commented on README.md
> +**01::** instalar docker desktop
Perfeito Gustavo, eu também vejo assim.

2021-07-20 11:13 UTC, ricardopacheco commented on app/controllers/addresses_controller.rb
> +      format.html { redirect_to addresses_url, notice: "Address was successfully destroyed." }
No caso como é o address a doc permite seguir por essa linha também. Pode ser destruido por aqui ou por accepted_nested_attributes_for (citzen => { ..., address: { id: 1, _destroy: true }} (exemplo).

2021-07-20 11:14 UTC, ricardopacheco commented on app/controllers/citizens_controller.rb
> +  # GET /citizens/new
Eles foram gerados automaticamente por scaffold. Quem conhece Rest e em casos simples, é desnecessário o comentário.

2021-07-20 18:04 UTC, eduardovrocha commented on .ruby-version
> +ruby-2.7.2@om30
então, o 'rvm' tem uma flag que suprime o 'warning message' e mantém a leitura do .ruby-version como definição pro ruby utilizado. Eu deixo o 'ruby-2.7.2@om30' local, mas para fazer deploy vai só 'ruby-2.7.2' ..

2021-07-20 18:07 UTC, eduardovrocha commented on README.md
> +**01::** instalar docker desktop
acredito q o Readme vai melhorando com tempo, já tenho alguns outros passos a listar no 'Instalação'

2021-07-20 18:09 UTC, eduardovrocha commented on README.md
> +## backend todo:
sim sim, concordo também, esse era só meu rascunho :)
mas concordo sobre a importancia / melhora q é utilizar a ferramenta apropriada

2021-07-20 18:11 UTC, eduardovrocha commented on app/controllers/addresses_controller.rb
> +  before_action :set_address, only: %i[ show edit update destroy ]
seria / também pode ser ...

2021-07-20 18:13 UTC, eduardovrocha commented on app/controllers/addresses_controller.rb
> +        format.html { redirect_to @address, notice: "Address was successfully created." }
então, eu deixei pq até o momento não defini q lado vou pro front, ou se vou focar pouco no front .. mas, o mais provável que eu caminhe sobre uma API

2021-07-20 18:13 UTC, eduardovrocha commented on app/controllers/addresses_controller.rb
> +        format.html { redirect_to @address, notice: "Address was successfully updated." }
ok ok

2021-07-20 18:16 UTC, eduardovrocha commented on app/controllers/citizens_controller.rb
> +  def destroy
concordo que seria um erro se fosse a entrega de teste / final ... aprovação ou apresentação. Até aqui não vejo como erro, mas tudo bem :)

2021-07-20 18:16 UTC, eduardovrocha commented on app/controllers/citizens_controller.rb
> +      format.html { redirect_to citizens_url, notice: "Citizen was successfully destroyed." }
ainda chego lá, tá listado

2021-07-20 18:17 UTC, eduardovrocha commented on app/helpers/citizens_helper.rb
> +module CitizensHelper
concordo :)

2021-07-20 18:18 UTC, eduardovrocha commented on app/views/addresses/_address.json.jbuilder
> +json.extract! address, :id, :cep, :full_place, :created_at, :updated_at
pois é, estou usando por/como padrão de criação de projeto, mas pode-se adotar outra view build json que a equipe achar adequado :)

2021-07-20 18:19 UTC, eduardovrocha commented on app/views/addresses/_form.html.erb
> +      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>
i18n será implementado hoje :)

2021-07-20 18:21 UTC, eduardovrocha commented on db/data/20210716210231_add_citizens.rb
> +class AddCitizens < SeedMigration::Migration
a organização como ela cria/deleta os record's junto com o 'versionamento' das migrations .. ela integra muito bacana com o active record, e tem uns truques interessantes ... preferência pessoal :)

2021-07-20 18:21 UTC, eduardovrocha commented on db/migrate/20210716195108_create_addresses.rb
> +      t.jsonb :full_place
uhmm, chegarei até lá

2021-07-20 21:01 UTC, ricardopacheco commented on app/views/addresses/_address.json.jbuilder
> +json.extract! address, :id, :cep, :full_place, :created_at, :updated_at
Projeto simples o jbuilder cai como uma luva! Performance nesse caso seria casos de maior uso! Pode continuar o/

2021-07-21 19:13 UTC, eduardovrocha reviewed
então, percorri cada comentário/apontamento, alterando no código seus aspectos, boa parte do código desse pull request é conteúdo padrão com ciclo curto

2021-07-21 21:33 UTC, gumiguelote approved these changes
- para seguir com as mudanças e não ficar tudo em um pr só

2021-07-21 21:58 UTC, merged